### ISSUE TITLE
Application will not start with .NET installed

### ISSUE THREAD

**Issue by Getmekenb** [Banzzouille/WahooFitToGarmin-Desktop#2]
Bonjour,
I downloaded and extracted your WahooFitToGarmin-Desktop files.
I installed the .NET Core version 3.1.23 x64 on my windows 7 64 bit OS PC.
When I launch the WahooFitToGarmin-Desktop application I get an the popup
"To run this application you must install the .NET Core.
The framework 'Microsoft.WindowsDesktop.App', version '3.1.0' was not found.
Would you like to download it now?"

I downloaded it again and repaired it. I restarted my system. Same error message.

Do you have a solution, Merci, Ken B.

**Comment by Banzzouille** [comment]
Hi!
thanks for trying my app.
Did you install this one ? 
[.NET Desktop Runtime 3.1.23](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.23-windows-x64-installer)
