### ISSUE TITLE
Deleting FIT files

### ISSUE THREAD

**Issue by Phil4286** [Banzzouille/WahooFitToGarmin-Desktop#3]
Hi Banzzouille, 
 Tool works as expected (thank you), except it deletes the fit files in dropbox when it transfers the activity to garmin.

I guess this doesn't bother everyone, but i have always uploaded to dropbox as a backup to strava etc and would like to continue keeping my backup files.

Phil.

**Comment by Banzzouille** [comment]
Hi Phil ! thank you for using my solution.
I can try to add an option in the settings tab to delete or not uploaded files to Garmin connect...

**Comment by Phil4286** [comment]
Something like that would be ideal.
I've always uploaded a copy from the Elemnt app to dropbox as a backup - that's what made your tool so convenient!

**Comment by Banzzouille** [comment]
Hi ! you can now use this new [release](https://github.com/Banzzouille/WahooFitToGarmin-Desktop/releases/tag/1.0.1)
