### ISSUE TITLE
No sync to garmin connect

### ISSUE THREAD

**Issue by geeheee** [Banzzouille/WahooFitToGarmin-Desktop#6]
Hi,
I've just installed your tool v1.0.1.0 (thanks in advance) and followed your instructions. I've updated the dropbox folder to watch, entered the garmin connect credentials (and verified they are correct) and restarted the app, and the app never connects to garmin. 
I've also reinstalled the app, restarted the PC, and changed the dropbox folder with no luck.

The log from the gui is:
Starting...
Wahoo folder to watch for C:\users etc.
--End--

In addition to this, in the appproperties json file when populated shows the below error:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Any ideas?

**Comment by Banzzouille** [comment]
Hi @geeheee ! 
Can you open the file located in your settings folder (C:\Users\%username%\AppData\Local\WahooFitToGarmin_Desktop\configuration\AppProperties.json) and try to decode the content with this site [for example](https://www.base64code.com/decode) 
You must have a result like this : 

{
    "Theme": "Default",
    "GarminLogin": "dfdfgh",
    "GarminPwd": "dfghdfgh",
    "WahooDropBoxFolder": "C:\\Users\\Me\\Desktop",
    "KeepUploadedActivityFile": false
}

If it's not the case, try to delete the settings file and relaunch the app.
Thanks

**Comment by geeheee** [comment]
Thanks for the advice.

I have deleted the original AppProperties, relaunched the app to create a new AppProperties file. After configuring the settings, and decoding the content, it is exactly as you've outlined, though unfortunately, the log shows that the no upload to garmin connect is taking place (also confirmed by garmin connect).

I've also started looking an antivirus/firewall as potential issues, but my results have remained the same.

![log](https://user-images.githubusercontent.com/108671110/177535667-e4216627-ff89-478d-931e-e509b8901e95.JPG)
![decode](https://user-images.githubusercontent.com/108671110/177535674-bff281c4-a6cc-46c0-b962-ca60610f7e10.JPG)

**Comment by Banzzouille** [comment]
This application checks if new files are coming to the folder you mention. If files are here before using WahooFitToGarmin_desktop app, no upload will be triggered. Try by moving an existing file from you WahooFitness folder to another one, then copy back to this folder, by running the application in background of course. It must triggered a notification and a try to upload this file to garmin servers.
