### ISSUE TITLE
402 Payment required

### ISSUE THREAD

**Issue by snanalol** [Banzzouille/WahooFitToGarmin-Desktop#7]
Hello

First of all, thanks for this app :) 

It seems there is an issue when uploading activities since month (worked fine this summer). 

![tempsnip](https://github.com/Banzzouille/WahooFitToGarmin-Desktop/assets/140850893/685b2e85-fed4-471e-aa1a-90af43a9a7e4)

The login part seems to work well, but the upload return an error.

https://github.com/Banzzouille/WahooFitToGarmin-Desktop/blob/d668c12b8afbe17dc66202ad363b86b9f20f1299/WahooFitToGarmin-Desktop/ViewModels/MainViewModel.cs#L86-L97

Am I alone ? Is there any subscription in garmin to be able to upload activities?  

BR

EDIT: I tried to request access to the api using this link https://developer.garmin.com/gc-developer-program/activity-api/ . I keep you in touch.
EDIT: Rejected :(

**Comment by Banzzouille** [comment]
Hi and thanks for your feedback,

it's been a really long time i pushed the last update on this project
I no longer use a Wahoo device and switched back to Garmin.
I can try to have a look on this error but i'm not really sure to be able to solve that.
I also received a rejection from the Garmin api enrolment without a real explanation...
We can switch to french if you prefer

regards,
Florian

**Comment by snanalol** [comment]
Garmin system is too much closed...  :( 

Let see if others have the same issue... I'm not sure it's related to your code, or my account.

**Comment by lorro** [comment]
I can confirm I have this issue too since a couple of weeks ;-)

**Comment by fehob** [comment]
I had the same issue this summer and autumn, sometimes a .fit file would fail to upload. I had to move it out and back into the Dropbox folder a few times before the upload would succeed. Only one time after lots of retries I had to manually add the file from Garmin Connect website.

Adding a retry on the upload would be a quick fix, but probably not a long time solution.

**Comment by Banzzouille** [comment]
Hi !
thanks for the detail.
i can try to change a little the behavior of the file management by adding a list of uploaded files.
I will also have to find a other way to trigger the file upload to be able to do retries.

By the way, i asked for an api access long time ago to Garmin and that was a simple reject.
I did it again 2 weeks again .... another reject...
How is it possible this company is so closed to little dev. We can add so more values to them ...

Thanks for your feedback ,
Florian

**Comment by snanalol** [comment]
Not sure a retry could solve the issue. (I tried it a lot :D) 

It's just an other marketing strategy to buy Garmin GPS....

**Comment by Banzzouille** [comment]
Hi there,
i pushed a new release package.
With this one, i'm able to push again activities to Garmin server

Regards,
Florian

**Comment by Hilroy300** [comment]
Big thank you for keeping this tool alive!

I got a Garmin Vivomove sport watch for my birthday and the watch does not even support Garmin's own Heart Rate Monitor (HRM Dual)...
I was able to use the HRM Dual chest strap with the Wahoo Fitness App to record time spent in different activity zones but so far the Intensity minutes are not correctly calculated when importing a .fit file.
Any idea about this?
I hope I don't have to buy another Garmin thing just to make this Heart Rate Monitor work.

**Comment by snanalol** [comment]
Congratz ! 

What's the issue ? A garmin breaking change in the auth method ?

**Comment by Banzzouille** [comment]
Yes exactly, i read a lot of public github code in multiple languages to have an idea of how they are doing the auth and the push. Unfortunately, my code becomes to be old and difficult to update. i will maybe rewrite it entirely one day, but when .... :D
