### ISSUE TITLE
Uploader appears to stall

### ISSUE THREAD

**Issue by adamdrewbernstein** [Banzzouille/WahooFitToGarmin-Desktop#9]
Hi Banzzouille, thanks for this great tool!

Unfortunately I've not been able to get it working. After following all parts of the step by step guide I have Dropbox connected in the Wahoo app, one activity sent to Dropbox and appearing in my local Dropbox client's folder, and the WahooFitToGarmin-Desktop v1.1.0 application installed and configured including with the path to my local Dropbox folder (C:\Users\Adam Bernstein\Dropbox\Apps\WahooFitness) and my Garmin signin credentials.

However on restart the app seems to stall after reporting the following in the log:
    Starting.......
    Wahoo folder to watch for : ...
    Starting uploader .......

I also tried version 1.01 of WahooFitToGarmin-Desktop, and it has basically the same behavior, stalling after:
    Starting.......
    Wahoo folder to watch for : ...

Anything you would advise? Thanks in advance for any thoughts!

**Comment by Banzzouille** [comment]
Hi Adam,
can you copy paste exactly the content of the log box? 
Normaly you must have a line "a new file is coming" that appears when Dropbox sync the file on your conputer.
If you launch the app after dropbox finish the sync maybe the app is not able to detect the new file.
In this case you can just move the file to another place on your computer and replace again in the folder you set in the configuration.
The app should at this time detect a "new file"

Florian

**Comment by adamdrewbernstein** [comment]
Thank you Florian! That did it, the problem was indeed that the file was
already present. Removing and replacing it initiated the upload.

Warmly,
Adam
